import type { ExerciseCategory, MetricType } from '@/types/db';

export interface SeedExercise {
  /** Clave estable para referenciar el ejercicio desde las sesiones demo. */
  slug: string;
  name: string;
  category: ExerciseCategory;
  metricType: MetricType;
  movementType: string;
  muscles: string[];
  equipment: string[];
  description: string;
  technique: string;
}

/**
 * Biblioteca inicial de LORDGYM (§34). Son ejercicios globales:
 * `owner_coach_id = null`, visibles para todos los entrenadores y no editables.
 */
export const EXERCISE_LIBRARY: SeedExercise[] = [
  // --- Pecho ---------------------------------------------------------------
  {
    slug: 'press-banca',
    name: 'Press banca',
    category: 'pecho',
    metricType: 'strength',
    movementType: 'Empuje horizontal',
    muscles: ['Pectoral mayor', 'Tríceps', 'Deltoides anterior'],
    equipment: ['Barra', 'Banco'],
    description: 'Empuje horizontal con barra tumbado en banco plano.',
    technique: 'Escápulas retraídas, pies firmes, barra a la línea del pecho y empuje sin perder el arco.',
  },
  {
    slug: 'press-banca-mancuernas',
    name: 'Press banca con mancuernas',
    category: 'pecho',
    metricType: 'strength',
    movementType: 'Empuje horizontal',
    muscles: ['Pectoral mayor', 'Tríceps'],
    equipment: ['Mancuernas', 'Banco'],
    description: 'Variante unilateral que permite mayor recorrido y control escapular.',
    technique: 'Codos a 45°, muñecas neutras, baja hasta notar estiramiento sin forzar el hombro.',
  },
  {
    slug: 'press-inclinado',
    name: 'Press inclinado',
    category: 'pecho',
    metricType: 'strength',
    movementType: 'Empuje inclinado',
    muscles: ['Pectoral superior', 'Deltoides anterior'],
    equipment: ['Barra', 'Banco inclinado'],
    description: 'Press con banco a 30–45° que enfatiza la porción clavicular.',
    technique: 'Evita elevar los hombros; la barra baja a la parte alta del pecho.',
  },
  {
    slug: 'flexiones',
    name: 'Flexiones',
    category: 'pecho',
    metricType: 'bodyweight',
    movementType: 'Empuje horizontal',
    muscles: ['Pectoral', 'Tríceps', 'Core'],
    equipment: [],
    description: 'Empuje horizontal con peso corporal.',
    technique: 'Cuerpo en línea, glúteo activo, codos cerca del tronco.',
  },
  {
    slug: 'fondos',
    name: 'Fondos en paralelas',
    category: 'pecho',
    metricType: 'bodyweight',
    movementType: 'Empuje vertical',
    muscles: ['Pectoral inferior', 'Tríceps'],
    equipment: ['Paralelas'],
    description: 'Empuje vertical descendente en paralelas.',
    technique: 'Ligera inclinación del tronco, baja hasta 90° de codo sin hundir el hombro.',
  },

  // --- Espalda -------------------------------------------------------------
  {
    slug: 'dominadas',
    name: 'Dominadas',
    category: 'espalda',
    metricType: 'bodyweight',
    movementType: 'Tracción vertical',
    muscles: ['Dorsal ancho', 'Bíceps', 'Romboides'],
    equipment: ['Barra fija'],
    description: 'Tracción vertical con agarre prono.',
    technique: 'Inicia deprimiendo escápulas; sube hasta pasar la barbilla sin balanceo.',
  },
  {
    slug: 'remo-mancuerna',
    name: 'Remo con mancuerna',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción horizontal',
    muscles: ['Dorsal ancho', 'Trapecio medio', 'Bíceps'],
    equipment: ['Mancuerna', 'Banco'],
    description: 'Tracción horizontal unilateral con apoyo en banco.',
    technique: 'Espalda neutra, tira con el codo hacia la cadera sin rotar el tronco.',
  },
  {
    slug: 'remo-barra',
    name: 'Remo con barra',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción horizontal',
    muscles: ['Dorsal ancho', 'Erectores', 'Trapecio'],
    equipment: ['Barra'],
    description: 'Remo con tronco inclinado a unos 45°.',
    technique: 'Bisagra de cadera, core firme, barra al ombligo.',
  },
  {
    slug: 'jalon-polea',
    name: 'Jalón al pecho',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción vertical',
    muscles: ['Dorsal ancho', 'Bíceps'],
    equipment: ['Polea alta'],
    description: 'Alternativa guiada a la dominada.',
    technique: 'Pecho arriba, lleva la barra a la clavícula sin echar el tronco atrás.',
  },
  {
    slug: 'peso-muerto',
    name: 'Peso muerto',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Bisagra de cadera',
    muscles: ['Isquiotibiales', 'Glúteo', 'Erectores'],
    equipment: ['Barra'],
    description: 'Levantamiento desde el suelo con bisagra de cadera.',
    technique: 'Barra pegada a la pierna, espalda neutra, extiende cadera y rodilla a la vez.',
  },
  {
    slug: 'face-pull',
    name: 'Face pull',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción horizontal alta',
    muscles: ['Deltoides posterior', 'Trapecio medio', 'Manguito rotador'],
    equipment: ['Polea', 'Cuerda'],
    description: 'Tracción a la cara para salud del hombro.',
    technique: 'Codos altos, rotación externa al final del recorrido.',
  },

  // --- Hombro --------------------------------------------------------------
  {
    slug: 'press-militar',
    name: 'Press militar',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Empuje vertical',
    muscles: ['Deltoides', 'Tríceps', 'Core'],
    equipment: ['Barra'],
    description: 'Empuje vertical de pie con barra.',
    technique: 'Glúteo y abdomen activos, la barra pasa cerca de la cara, bloquea arriba.',
  },
  {
    slug: 'landmine-press',
    name: 'Landmine press',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Empuje inclinado unilateral',
    muscles: ['Deltoides anterior', 'Serrato', 'Core'],
    equipment: ['Barra', 'Landmine'],
    description: 'Empuje en diagonal muy amable con el hombro.',
    technique: 'Postura estable, empuja en diagonal ascendente y protrae la escápula al final.',
  },
  {
    slug: 'elevaciones-laterales',
    name: 'Elevaciones laterales',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Abducción',
    muscles: ['Deltoides medio'],
    equipment: ['Mancuernas'],
    description: 'Aislamiento del deltoides medio.',
    technique: 'Sube hasta la altura del hombro sin encoger el trapecio.',
  },

  // --- Brazo ---------------------------------------------------------------
  {
    slug: 'curl-biceps',
    name: 'Curl de bíceps',
    category: 'biceps',
    metricType: 'strength',
    movementType: 'Flexión de codo',
    muscles: ['Bíceps braquial', 'Braquial'],
    equipment: ['Mancuernas'],
    description: 'Flexión de codo con mancuernas.',
    technique: 'Codos pegados al tronco, sin balanceo lumbar.',
  },
  {
    slug: 'curl-martillo',
    name: 'Curl martillo',
    category: 'biceps',
    metricType: 'strength',
    movementType: 'Flexión de codo neutra',
    muscles: ['Braquiorradial', 'Bíceps'],
    equipment: ['Mancuernas'],
    description: 'Curl con agarre neutro.',
    technique: 'Muñeca neutra durante todo el recorrido.',
  },
  {
    slug: 'extension-triceps-polea',
    name: 'Extensión de tríceps en polea',
    category: 'triceps',
    metricType: 'strength',
    movementType: 'Extensión de codo',
    muscles: ['Tríceps'],
    equipment: ['Polea'],
    description: 'Aislamiento de tríceps en polea alta.',
    technique: 'Codos fijos, extiende completamente sin mover el hombro.',
  },

  // --- Pierna --------------------------------------------------------------
  {
    slug: 'sentadilla',
    name: 'Sentadilla',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Dominante de rodilla',
    muscles: ['Cuádriceps', 'Glúteo', 'Aductores'],
    equipment: ['Barra', 'Rack'],
    description: 'Sentadilla trasera con barra.',
    technique: 'Rodillas siguiendo la punta del pie, tronco firme, baja al menos a paralelo.',
  },
  {
    slug: 'sentadilla-bulgara',
    name: 'Sentadilla búlgara',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Unilateral dominante de rodilla',
    muscles: ['Cuádriceps', 'Glúteo'],
    equipment: ['Mancuernas', 'Banco'],
    description: 'Zancada elevada unilateral, clave en deportes de equipo.',
    technique: 'Pie trasero apoyado en el banco, baja controlando la rodilla delantera.',
  },
  {
    slug: 'peso-muerto-rumano',
    name: 'Peso muerto rumano',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Bisagra de cadera',
    muscles: ['Isquiotibiales', 'Glúteo'],
    equipment: ['Barra'],
    description: 'Bisagra de cadera con rodillas semiflexionadas.',
    technique: 'Lleva la cadera atrás, espalda neutra, baja hasta notar tensión isquiotibial.',
  },
  {
    slug: 'hip-thrust',
    name: 'Hip thrust',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Extensión de cadera',
    muscles: ['Glúteo mayor', 'Isquiotibiales'],
    equipment: ['Barra', 'Banco'],
    description: 'Extensión de cadera con apoyo escapular en banco.',
    technique: 'Barbilla al pecho, bloquea arriba apretando el glúteo sin hiperextender lumbar.',
  },
  {
    slug: 'nordic-curl',
    name: 'Nordic curl',
    category: 'prevencion',
    metricType: 'bodyweight',
    movementType: 'Excéntrico isquiotibial',
    muscles: ['Isquiotibiales'],
    equipment: ['Compañero o anclaje'],
    description: 'Ejercicio excéntrico de referencia para prevenir lesiones de isquiotibiales.',
    technique: 'Baja lo más lento posible manteniendo cadera extendida.',
  },
  {
    slug: 'elevacion-talones',
    name: 'Elevación de talones',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Flexión plantar',
    muscles: ['Gastrocnemio', 'Sóleo'],
    equipment: ['Step'],
    description: 'Trabajo de tríceps sural y rigidez del tobillo.',
    technique: 'Recorrido completo, pausa arriba de un segundo.',
  },

  // --- Core ----------------------------------------------------------------
  {
    slug: 'pallof-press',
    name: 'Pallof press',
    category: 'core',
    metricType: 'strength',
    movementType: 'Anti-rotación',
    muscles: ['Oblicuos', 'Transverso'],
    equipment: ['Polea', 'Banda'],
    description: 'Anti-rotación isométrica, muy transferible al gesto deportivo.',
    technique: 'Aleja las manos del pecho resistiendo la rotación; sin mover la cadera.',
  },
  {
    slug: 'plancha',
    name: 'Plancha frontal',
    category: 'core',
    metricType: 'time',
    movementType: 'Isométrico',
    muscles: ['Transverso', 'Recto abdominal'],
    equipment: [],
    description: 'Isométrico de core en posición prona.',
    technique: 'Pelvis en retroversión, glúteo activo, sin hundir lumbares.',
  },
  {
    slug: 'dead-bug',
    name: 'Dead bug',
    category: 'core',
    metricType: 'strength',
    movementType: 'Anti-extensión',
    muscles: ['Transverso', 'Recto abdominal'],
    equipment: [],
    description: 'Control lumbopélvico con movimiento contralateral.',
    technique: 'Zona lumbar pegada al suelo durante todo el movimiento.',
  },
  {
    slug: 'copenhagen-plank',
    name: 'Copenhagen plank',
    category: 'prevencion',
    metricType: 'time',
    movementType: 'Isométrico aductor',
    muscles: ['Aductores', 'Core'],
    equipment: ['Banco'],
    description: 'Isométrico de aductores usado en prevención de pubalgia.',
    technique: 'Pierna superior apoyada en el banco, cadera alineada.',
  },

  // --- Pliometría ----------------------------------------------------------
  {
    slug: 'box-jump',
    name: 'Box jump',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Salto vertical',
    muscles: ['Cuádriceps', 'Glúteo', 'Gemelos'],
    equipment: ['Cajón'],
    description: 'Salto vertical sobre cajón. Calidad por encima de cantidad.',
    technique: 'Aterriza suave y con rodillas alineadas; baja del cajón caminando.',
  },
  {
    slug: 'cmj',
    name: 'CMJ (salto con contramovimiento)',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Salto vertical',
    muscles: ['Extensores de cadera y rodilla'],
    equipment: [],
    description: 'Salto vertical con contramovimiento, referencia de potencia.',
    technique: 'Manos en la cadera, contramovimiento rápido, salto máximo.',
  },
  {
    slug: 'broad-jump',
    name: 'Broad jump',
    category: 'pliometria',
    metricType: 'distance',
    movementType: 'Salto horizontal',
    muscles: ['Glúteo', 'Isquiotibiales', 'Cuádriceps'],
    equipment: [],
    description: 'Salto horizontal a máxima distancia.',
    technique: 'Brazos acompañan, aterrizaje amortiguado con dos pies.',
  },
  {
    slug: 'depth-jump',
    name: 'Depth jump',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Ciclo estiramiento-acortamiento',
    muscles: ['Tríceps sural', 'Cuádriceps'],
    equipment: ['Cajón'],
    description: 'Caída desde cajón y salto inmediato. Alta demanda neuromuscular.',
    technique: 'Contacto con el suelo mínimo; sólo con base de fuerza previa.',
  },
  {
    slug: 'pogo-jumps',
    name: 'Pogo jumps',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Rigidez de tobillo',
    muscles: ['Gemelos', 'Sóleo'],
    equipment: [],
    description: 'Saltos cortos y rápidos para trabajar rigidez del tobillo.',
    technique: 'Rodillas casi extendidas, rebota con el tobillo.',
  },

  // --- Velocidad y agilidad ------------------------------------------------
  {
    slug: 'sprint-10m',
    name: 'Sprint 10 m',
    category: 'velocidad',
    metricType: 'distance',
    movementType: 'Aceleración',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Aceleración corta desde parado.',
    technique: 'Salida con inclinación, primeros apoyos por detrás del centro de masas.',
  },
  {
    slug: 'sprint-20m',
    name: 'Sprint 20 m',
    category: 'velocidad',
    metricType: 'distance',
    movementType: 'Aceleración',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Aceleración media, referencia clásica en deportes de equipo.',
    technique: 'Transición progresiva de la inclinación a la posición erguida.',
  },
  {
    slug: 'sprint-30m',
    name: 'Sprint 30 m',
    category: 'velocidad',
    metricType: 'distance',
    movementType: 'Velocidad máxima',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Sprint hasta velocidad máxima.',
    technique: 'Zancada amplia y activa, contacto breve con el suelo.',
  },
  {
    slug: 'cambio-direccion',
    name: 'Cambios de dirección',
    category: 'agilidad',
    metricType: 'time',
    movementType: 'COD',
    muscles: ['Tren inferior', 'Core'],
    equipment: ['Conos'],
    description: 'Circuito de cambios de dirección a máxima intensidad.',
    technique: 'Baja el centro de gravedad antes del cambio y reorienta la cadera.',
  },
  {
    slug: 'test-5-10-5',
    name: '5-10-5 (pro agility)',
    category: 'agilidad',
    metricType: 'time',
    movementType: 'COD',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Test de agilidad con dos cambios de 180°.',
    technique: 'Frenada con pie externo y salida explosiva.',
  },
  {
    slug: 't-test',
    name: 'T-Test',
    category: 'agilidad',
    metricType: 'time',
    movementType: 'COD multidireccional',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Test en T con desplazamientos frontal, lateral y atrás.',
    technique: 'Sin cruzar los pies en el desplazamiento lateral.',
  },

  // --- Movilidad y prevención ---------------------------------------------
  {
    slug: 'movilidad-cadera',
    name: 'Movilidad de cadera 90/90',
    category: 'movilidad',
    metricType: 'time',
    movementType: 'Movilidad activa',
    muscles: ['Rotadores de cadera'],
    equipment: [],
    description: 'Rotación activa de cadera en posición 90/90.',
    technique: 'Tronco erguido, movimiento controlado sin compensar con lumbar.',
  },
  {
    slug: 'movilidad-toracica',
    name: 'Movilidad torácica en cuadrupedia',
    category: 'movilidad',
    metricType: 'time',
    movementType: 'Movilidad activa',
    muscles: ['Columna torácica'],
    equipment: [],
    description: 'Rotación torácica con mano en la nuca.',
    technique: 'Bloquea la lumbar y rota sólo desde la zona dorsal.',
  },
  {
    slug: 'movilidad-tobillo',
    name: 'Movilidad de tobillo en pared',
    category: 'movilidad',
    metricType: 'time',
    movementType: 'Dorsiflexión',
    muscles: ['Tobillo'],
    equipment: ['Pared'],
    description: 'Test y ejercicio de dorsiflexión.',
    technique: 'Talón en el suelo, rodilla hacia la pared sin abrir el pie.',
  },
  {
    slug: 'monster-walk',
    name: 'Monster walk con banda',
    category: 'prevencion',
    metricType: 'time',
    movementType: 'Activación glútea',
    muscles: ['Glúteo medio'],
    equipment: ['Banda elástica'],
    description: 'Activación de glúteo medio en desplazamiento lateral.',
    technique: 'Rodillas separadas, pasos cortos, sin balancear el tronco.',
  },
  {
    slug: 'isquios-excentrico',
    name: 'Excéntrico de isquiotibiales en deslizamiento',
    category: 'rehabilitacion',
    metricType: 'strength',
    movementType: 'Excéntrico',
    muscles: ['Isquiotibiales'],
    equipment: ['Deslizadores'],
    description: 'Progresión de fuerza excéntrica en fases de readaptación.',
    technique: 'Extiende las piernas lentamente manteniendo la cadera alta.',
  },
  {
    slug: 'propiocepcion-tobillo',
    name: 'Propiocepción unipodal',
    category: 'rehabilitacion',
    metricType: 'time',
    movementType: 'Estabilidad',
    muscles: ['Tobillo', 'Core'],
    equipment: ['Bosu opcional'],
    description: 'Equilibrio a una pierna, base de la readaptación de tobillo.',
    technique: 'Mirada al frente, rodilla ligeramente flexionada, sin apoyar la otra pierna.',
  },

  // --- Cardio --------------------------------------------------------------
  {
    slug: 'carrera-continua',
    name: 'Carrera continua',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Aeróbico',
    muscles: ['Sistema cardiovascular'],
    equipment: [],
    description: 'Trabajo aeróbico continuo a intensidad controlada.',
    technique: 'Respiración cómoda; mantén la zona de FC objetivo.',
  },
  {
    slug: 'bici-estatica',
    name: 'Bicicleta estática',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Aeróbico',
    muscles: ['Cuádriceps', 'Sistema cardiovascular'],
    equipment: ['Bicicleta'],
    description: 'Cardio de bajo impacto, útil en cargas altas o readaptación.',
    technique: 'Sillín a la altura de la cadera; cadencia estable.',
  },
  {
    slug: 'remo-ergometro',
    name: 'Remo ergómetro',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Aeróbico de cuerpo completo',
    muscles: ['Espalda', 'Piernas', 'Sistema cardiovascular'],
    equipment: ['Remo'],
    description: 'Cardio de cuerpo completo con bajo impacto articular.',
    technique: 'Secuencia piernas → tronco → brazos; vuelve en orden inverso.',
  },
  {
    slug: 'intervalos-30-30',
    name: 'Intervalos 30/30',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Intervalos',
    muscles: ['Sistema cardiovascular'],
    equipment: [],
    description: '30 segundos de carrera intensa por 30 de recuperación.',
    technique: 'Mantén el ritmo objetivo en todas las repeticiones.',
  },
  // --- Calistenia ----------------------------------------------------------
  {
    slug: 'muscle-up',
    name: 'Muscle-up',
    category: 'calistenia',
    metricType: 'bodyweight',
    movementType: 'Tracción explosiva y transición',
    muscles: ['Dorsal ancho', 'Pectoral', 'Tríceps', 'Core'],
    equipment: ['Barra fija'],
    description: 'Dominada explosiva encadenada con un fondo para acabar con el pecho por encima de la barra.',
    technique: 'Tira hacia el esternón con el pecho alto, gira las muñecas al pasar la barra y empuja hasta bloquear los codos.',
  },
  {
    slug: 'dominadas-supinas',
    name: 'Dominadas supinas',
    category: 'espalda',
    metricType: 'bodyweight',
    movementType: 'Tracción vertical supina',
    muscles: ['Dorsal ancho', 'Bíceps'],
    equipment: ['Barra fija'],
    description: 'Dominada con las palmas hacia ti: más recorrido de bíceps que la prona.',
    technique: 'Codos pegados al cuerpo, sube sin balanceo y baja controlando hasta estirar del todo.',
  },
  {
    slug: 'dominadas-lastradas',
    name: 'Dominadas lastradas',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción vertical con carga',
    muscles: ['Dorsal ancho', 'Bíceps', 'Romboides'],
    equipment: ['Barra fija', 'Cinturón de lastre'],
    description: 'Dominada con peso añadido para seguir progresando cuando el peso corporal se queda corto.',
    technique: 'Añade carga sólo si haces 8 limpias. Mantén el recorrido completo: barbilla arriba, brazos estirados abajo.',
  },
  {
    slug: 'remo-invertido',
    name: 'Remo invertido',
    category: 'espalda',
    metricType: 'bodyweight',
    movementType: 'Tracción horizontal con peso corporal',
    muscles: ['Dorsal ancho', 'Romboides', 'Bíceps'],
    equipment: ['Barra fija'],
    description: 'Remo tumbado bajo una barra baja. La progresión natural hacia la dominada.',
    technique: 'Cuerpo en línea, lleva el esternón a la barra y aprieta las escápulas. Cuanto más horizontal, más difícil.',
  },
  {
    slug: 'flexiones-diamante',
    name: 'Flexiones diamante',
    category: 'triceps',
    metricType: 'bodyweight',
    movementType: 'Empuje horizontal cerrado',
    muscles: ['Tríceps', 'Pectoral interno'],
    equipment: [],
    description: 'Flexión con las manos juntas formando un rombo: el tríceps se lleva casi todo el trabajo.',
    technique: 'Índices y pulgares en contacto bajo el esternón, codos rozando el tronco.',
  },
  {
    slug: 'flexiones-arquero',
    name: 'Flexiones arquero',
    category: 'pecho',
    metricType: 'bodyweight',
    movementType: 'Empuje horizontal unilateral',
    muscles: ['Pectoral mayor', 'Tríceps'],
    equipment: [],
    description: 'Flexión cargando el peso en un brazo mientras el otro se estira. Paso previo a la flexión a una mano.',
    technique: 'Baja hacia una mano manteniendo el otro brazo estirado. Cadera cuadrada, sin rotar.',
  },
  {
    slug: 'flexiones-pica',
    name: 'Flexiones en pica',
    category: 'hombro',
    metricType: 'bodyweight',
    movementType: 'Empuje vertical con peso corporal',
    muscles: ['Deltoides', 'Tríceps'],
    equipment: [],
    description: 'Flexión con la cadera alta: el empuje pasa a ser casi vertical. Camino hacia el pino.',
    technique: 'Cadera lo más alta posible, baja la coronilla hacia el suelo entre las manos.',
  },
  {
    slug: 'flexiones-declinadas',
    name: 'Flexiones declinadas',
    category: 'pecho',
    metricType: 'bodyweight',
    movementType: 'Empuje inclinado',
    muscles: ['Pectoral superior', 'Deltoides anterior'],
    equipment: ['Cajón'],
    description: 'Flexión con los pies elevados: más carga y más pectoral clavicular.',
    technique: 'Cuerpo en línea desde los talones hasta la cabeza; no dejes caer la cadera.',
  },
  {
    slug: 'fondos-banco',
    name: 'Fondos en banco',
    category: 'triceps',
    metricType: 'bodyweight',
    movementType: 'Extensión de codo con peso corporal',
    muscles: ['Tríceps', 'Deltoides anterior'],
    equipment: ['Banco'],
    description: 'Fondo con las manos apoyadas detrás en un banco y los pies delante.',
    technique: 'Baja hasta 90° de codo con la espalda pegada al banco. Si molesta el hombro, reduce el recorrido.',
  },
  {
    slug: 'pino',
    name: 'Pino',
    category: 'calistenia',
    metricType: 'time',
    movementType: 'Isométrico invertido',
    muscles: ['Deltoides', 'Core', 'Antebrazo'],
    equipment: [],
    description: 'Vertical sobre las manos. Base de todo el trabajo de empuje invertido.',
    technique: 'Manos a la anchura de los hombros, dedos agarrando el suelo, costillas metidas y glúteo apretado.',
  },
  {
    slug: 'flexiones-pino',
    name: 'Flexiones en pino',
    category: 'hombro',
    metricType: 'bodyweight',
    movementType: 'Empuje vertical invertido',
    muscles: ['Deltoides', 'Tríceps', 'Trapecio'],
    equipment: [],
    description: 'Flexión haciendo el pino: el empuje vertical más exigente con peso corporal.',
    technique: 'Baja la cabeza hasta el suelo formando un triángulo con las manos y empuja sin arquear la espalda.',
  },
  {
    slug: 'l-sit',
    name: 'L-sit',
    category: 'core',
    metricType: 'time',
    movementType: 'Isométrico compresivo',
    muscles: ['Recto abdominal', 'Flexores de cadera', 'Cuádriceps'],
    equipment: ['Paralelas'],
    description: 'Sostenerse sobre las manos con las piernas estiradas en ángulo recto.',
    technique: 'Hombros abajo y lejos de las orejas, rodillas bloqueadas y punteras estiradas.',
  },
  {
    slug: 'front-lever',
    name: 'Front lever',
    category: 'calistenia',
    metricType: 'time',
    movementType: 'Isométrico horizontal',
    muscles: ['Dorsal ancho', 'Core', 'Romboides'],
    equipment: ['Barra fija'],
    description: 'Cuerpo horizontal colgado de la barra, mirando arriba. Fuerza de tracción en estado puro.',
    technique: 'Brazos rectos, escápulas deprimidas, cadera en retroversión. Progresa por etapas: rodillas, una pierna, completo.',
  },
  {
    slug: 'planche',
    name: 'Planche',
    category: 'calistenia',
    metricType: 'time',
    movementType: 'Isométrico horizontal de empuje',
    muscles: ['Deltoides anterior', 'Pectoral', 'Core'],
    equipment: [],
    description: 'Cuerpo horizontal sostenido sólo con las manos, sin apoyo de pies.',
    technique: 'Protrae los hombros y échalos por delante de las manos. Progresa desde tuck y straddle.',
  },
  {
    slug: 'bandera',
    name: 'Bandera humana',
    category: 'calistenia',
    metricType: 'time',
    movementType: 'Isométrico lateral',
    muscles: ['Oblicuos', 'Dorsal ancho', 'Deltoides'],
    equipment: ['Barra vertical'],
    description: 'Cuerpo horizontal agarrado a una barra vertical. El gran isométrico de oblicuos.',
    technique: 'El brazo de arriba tira y el de abajo empuja. Empieza en tuck y ve abriendo las piernas.',
  },
  {
    slug: 'sentadilla-pistol',
    name: 'Sentadilla pistol',
    category: 'pierna',
    metricType: 'bodyweight',
    movementType: 'Dominante de rodilla unilateral',
    muscles: ['Cuádriceps', 'Glúteo', 'Core'],
    equipment: [],
    description: 'Sentadilla a una pierna con la otra estirada al frente.',
    technique: 'Baja despacio con el talón clavado y el tronco algo inclinado. Si te falta movilidad de tobillo, eleva el talón.',
  },
  {
    slug: 'zancadas',
    name: 'Zancadas',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Unilateral dominante de rodilla',
    muscles: ['Cuádriceps', 'Glúteo', 'Isquiotibiales'],
    equipment: ['Mancuernas'],
    description: 'Paso largo bajando la rodilla de atrás casi al suelo, alternando piernas.',
    technique: 'Tronco vertical, rodilla de delante en línea con el pie, empuja con el talón para volver.',
  },
  {
    slug: 'elevacion-piernas-barra',
    name: 'Elevación de piernas en barra',
    category: 'core',
    metricType: 'bodyweight',
    movementType: 'Flexión de cadera colgado',
    muscles: ['Recto abdominal', 'Flexores de cadera', 'Oblicuos'],
    equipment: ['Barra fija'],
    description: 'Colgado de la barra, subir las piernas rectas hasta la horizontal o más.',
    technique: 'Sin balanceo: primero mete la pelvis y luego sube. Baja controlando, no dejes caer.',
  },
  {
    slug: 'hollow-body',
    name: 'Hollow body',
    category: 'core',
    metricType: 'time',
    movementType: 'Anti-extensión',
    muscles: ['Recto abdominal', 'Transverso'],
    equipment: [],
    description: 'Isométrico boca arriba con hombros y piernas despegados del suelo.',
    technique: 'Lumbar pegada al suelo todo el rato. Si se despega, sube las piernas.',
  },
  {
    slug: 'superman',
    name: 'Superman',
    category: 'prevencion',
    metricType: 'time',
    movementType: 'Extensión de columna',
    muscles: ['Erectores espinales', 'Glúteo'],
    equipment: [],
    description: 'Boca abajo, levantando brazos y piernas a la vez.',
    technique: 'Alarga en vez de arquear: estira brazos y piernas lejos, con la mirada al suelo.',
  },
  {
    slug: 'puente-gluteo',
    name: 'Puente de glúteo',
    category: 'pierna',
    metricType: 'bodyweight',
    movementType: 'Extensión de cadera',
    muscles: ['Glúteo mayor', 'Isquiotibiales'],
    equipment: [],
    description: 'Extensión de cadera tumbado: la versión sin material del hip thrust.',
    technique: 'Empuja con los talones y aprieta el glúteo arriba sin arquear la lumbar.',
  },
  {
    slug: 'burpee',
    name: 'Burpee',
    category: 'cardio',
    metricType: 'bodyweight',
    movementType: 'Cuerpo completo',
    muscles: ['Cuerpo completo'],
    equipment: [],
    description: 'Flexión en el suelo, salto a la posición de pie y salto vertical, encadenados.',
    technique: 'Pecho al suelo abajo y extensión completa de cadera arriba. Mejor ritmo constante que explosivo y roto.',
  },
  {
    slug: 'mountain-climbers',
    name: 'Escaladores',
    category: 'core',
    metricType: 'time',
    movementType: 'Anti-extensión dinámico',
    muscles: ['Core', 'Flexores de cadera', 'Deltoides'],
    equipment: [],
    description: 'En plancha, llevar las rodillas al pecho alternando rápido.',
    technique: 'La cadera no sube ni baja: el movimiento es sólo de piernas.',
  },
  {
    slug: 'sentadilla-salto',
    name: 'Sentadilla con salto',
    category: 'pliometria',
    metricType: 'bodyweight',
    movementType: 'Salto vertical desde sentadilla',
    muscles: ['Cuádriceps', 'Glúteo', 'Gemelo'],
    equipment: [],
    description: 'Sentadilla que termina despegando del suelo.',
    technique: 'Aterriza suave, con la rodilla mirando al pie, y encadena sin rebotar con la espalda.',
  },
  {
    slug: 'subida-cajon',
    name: 'Subida al cajón',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Unilateral dominante de rodilla',
    muscles: ['Cuádriceps', 'Glúteo'],
    equipment: ['Cajón', 'Mancuernas'],
    description: 'Subir a un cajón con una pierna, sin impulso de la de abajo.',
    technique: 'Todo el pie en el cajón y empuja con el talón. Baja controlando, no te dejes caer.',
  },
  {
    slug: 'rueda-abdominal',
    name: 'Rueda abdominal',
    category: 'core',
    metricType: 'bodyweight',
    movementType: 'Anti-extensión',
    muscles: ['Recto abdominal', 'Dorsal ancho', 'Transverso'],
    equipment: ['Rueda abdominal'],
    description: 'Desde las rodillas, rodar hacia delante sin que la lumbar se arquee.',
    technique: 'Costillas metidas y glúteo apretado. Llega sólo hasta donde puedas mantener la espalda plana.',
  },

  // --- Máquinas de gimnasio ------------------------------------------------
  {
    slug: 'prensa-piernas',
    name: 'Prensa de piernas',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Dominante de rodilla en máquina',
    muscles: ['Cuádriceps', 'Glúteo', 'Isquiotibiales'],
    equipment: ['Prensa'],
    description: 'Empuje de piernas en máquina, con la espalda apoyada y sin exigencia de core.',
    technique: 'Pies a la anchura de la cadera, no bloquees del todo las rodillas y no dejes que la lumbar se despegue.',
  },
  {
    slug: 'extension-cuadriceps',
    name: 'Extensión de cuádriceps',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Extensión de rodilla',
    muscles: ['Cuádriceps'],
    equipment: ['Máquina de extensión'],
    description: 'Aislamiento de cuádriceps sentado en máquina.',
    technique: 'Alinea el eje de la máquina con la rodilla. Sube hasta estirar y baja frenando.',
  },
  {
    slug: 'curl-femoral',
    name: 'Curl femoral',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Flexión de rodilla',
    muscles: ['Isquiotibiales', 'Gemelo'],
    equipment: ['Máquina de curl'],
    description: 'Aislamiento de isquiotibiales llevando el talón al glúteo.',
    technique: 'Cadera pegada al banco. Sube apretando y baja despacio: la fase excéntrica es la que protege.',
  },
  {
    slug: 'remo-sentado-polea',
    name: 'Remo sentado en polea',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción horizontal',
    muscles: ['Dorsal ancho', 'Romboides', 'Trapecio medio'],
    equipment: ['Polea baja'],
    description: 'Remo sentado con cable, con el tronco fijo.',
    technique: 'Pecho alto, lleva el agarre al ombligo juntando escápulas. No te eches atrás con la lumbar.',
  },
  {
    slug: 'press-pecho-maquina',
    name: 'Press de pecho en máquina',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Empuje horizontal guiado',
    muscles: ['Pectoral mayor', 'Tríceps', 'Deltoides anterior'],
    equipment: ['Máquina de press'],
    description: 'Empuje horizontal guiado: sirve para acumular volumen sin fatiga técnica.',
    technique: 'Ajusta el asiento para que los agarres queden a la altura del pecho. Escápulas apoyadas y retraídas.',
  },
  {
    slug: 'contractor-pectoral',
    name: 'Contractor pectoral',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Aducción horizontal',
    muscles: ['Pectoral mayor'],
    equipment: ['Máquina contractora'],
    description: 'Aislamiento de pectoral juntando los brazos por delante.',
    technique: 'Codos ligeramente flexionados y fijos. Junta hasta tocar y abre sin pasarte del plano del tronco.',
  },
  {
    slug: 'cruce-poleas',
    name: 'Cruce de poleas',
    category: 'pecho',
    metricType: 'strength',
    movementType: 'Aducción horizontal en cable',
    muscles: ['Pectoral mayor', 'Pectoral inferior'],
    equipment: ['Poleas altas'],
    description: 'Aislamiento de pectoral cruzando los cables por delante del cuerpo.',
    technique: 'Un paso adelante, tronco algo inclinado, cruza las manos bajo el esternón y aguanta un segundo.',
  },
  {
    slug: 'press-hombro-maquina',
    name: 'Press de hombro en máquina',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Empuje vertical guiado',
    muscles: ['Deltoides', 'Tríceps'],
    equipment: ['Máquina de press'],
    description: 'Press vertical guiado, con la espalda apoyada.',
    technique: 'Agarres a la altura de las orejas al empezar. No bloquees los codos de golpe arriba.',
  },
  {
    slug: 'pajaro-posterior',
    name: 'Pájaro (deltoides posterior)',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Abducción horizontal',
    muscles: ['Deltoides posterior', 'Trapecio medio', 'Romboides'],
    equipment: ['Mancuernas'],
    description: 'Aislamiento del deltoides posterior, el que casi siempre queda flojo.',
    technique: 'Tronco inclinado casi horizontal, sube con los codos y no con las manos. Poco peso, mucho control.',
  },
  {
    slug: 'encogimientos',
    name: 'Encogimientos de trapecio',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Elevación escapular',
    muscles: ['Trapecio superior'],
    equipment: ['Mancuernas'],
    description: 'Elevación de hombros hacia las orejas con carga en las manos.',
    technique: 'Sube recto, sin rotar los hombros, y aguanta arriba. Los brazos sólo sujetan.',
  },
  {
    slug: 'curl-predicador',
    name: 'Curl predicador',
    category: 'biceps',
    metricType: 'strength',
    movementType: 'Flexión de codo con brazo fijo',
    muscles: ['Bíceps braquial', 'Braquial'],
    equipment: ['Banco predicador', 'Barra Z'],
    description: 'Curl con el brazo apoyado en un banco inclinado: no hay forma de ayudarse con la espalda.',
    technique: 'Axila pegada al banco. Baja hasta casi estirar, sin soltar la tensión del codo.',
  },
  {
    slug: 'press-frances',
    name: 'Press francés',
    category: 'triceps',
    metricType: 'strength',
    movementType: 'Extensión de codo tumbado',
    muscles: ['Tríceps'],
    equipment: ['Barra Z', 'Banco'],
    description: 'Extensión de tríceps tumbado, bajando la barra hacia la frente.',
    technique: 'Codos quietos apuntando al techo. Si molestan, usa barra Z y reduce el recorrido.',
  },
  {
    slug: 'abductores-maquina',
    name: 'Abductores en máquina',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Abducción de cadera',
    muscles: ['Glúteo medio', 'Tensor de la fascia lata'],
    equipment: ['Máquina de abductores'],
    description: 'Aislamiento del glúteo medio, clave para la estabilidad de rodilla y cadera.',
    technique: 'Tronco recto o algo inclinado adelante. Abre hasta el final y vuelve frenando.',
  },
  {
    slug: 'gemelos-sentado',
    name: 'Gemelos sentado',
    category: 'gimnasio',
    metricType: 'strength',
    movementType: 'Flexión plantar con rodilla flexionada',
    muscles: ['Sóleo'],
    equipment: ['Máquina de gemelos'],
    description: 'Con la rodilla doblada el trabajo se va al sóleo, el músculo del salto repetido.',
    technique: 'Recorrido completo: talón bien abajo y subida hasta la punta del pie. Pausa arriba.',
  },
  {
    slug: 'sentadilla-frontal',
    name: 'Sentadilla frontal',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Dominante de rodilla',
    muscles: ['Cuádriceps', 'Core', 'Glúteo'],
    equipment: ['Barra'],
    description: 'Sentadilla con la barra delante: tronco más vertical y más cuádriceps que la trasera.',
    technique: 'Codos altos todo el rato. Si bajan, la barra se va hacia delante.',
  },
  {
    slug: 'sentadilla-goblet',
    name: 'Sentadilla goblet',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Dominante de rodilla',
    muscles: ['Cuádriceps', 'Glúteo', 'Core'],
    equipment: ['Mancuerna'],
    description: 'Sentadilla sujetando una mancuerna contra el pecho. La mejor para aprender el patrón.',
    technique: 'La mancuerna hace de contrapeso: úsala para bajar más recto y abrir rodillas.',
  },
  {
    slug: 'remo-menton',
    name: 'Remo al mentón',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Tracción vertical corta',
    muscles: ['Deltoides lateral', 'Trapecio'],
    equipment: ['Barra'],
    description: 'Tirón vertical corto con los codos por encima de las manos.',
    technique: 'No pases de la altura del pecho y usa agarre ancho: así el hombro no pellizca.',
  },
  {
    slug: 'buenos-dias',
    name: 'Buenos días',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Bisagra de cadera',
    muscles: ['Isquiotibiales', 'Glúteo', 'Erectores'],
    equipment: ['Barra'],
    description: 'Bisagra de cadera con la barra en la espalda. Refuerza toda la cadena posterior.',
    technique: 'Rodillas algo flexionadas y espalda plana. Empieza con muy poco peso: el brazo de palanca es largo.',
  },
  {
    slug: 'pull-over',
    name: 'Pull-over',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Extensión de hombro',
    muscles: ['Dorsal ancho', 'Pectoral', 'Serrato'],
    equipment: ['Mancuerna', 'Banco'],
    description: 'Tumbado, llevar la mancuerna de detrás de la cabeza al pecho con los brazos casi rectos.',
    technique: 'Costillas abajo para que el movimiento salga del hombro y no de la lumbar.',
  },
  {
    slug: 'abdominales-polea',
    name: 'Abdominales en polea',
    category: 'core',
    metricType: 'strength',
    movementType: 'Flexión de tronco con carga',
    muscles: ['Recto abdominal', 'Oblicuos'],
    equipment: ['Polea alta'],
    description: 'Encogimiento con cable: permite progresar en carga como en cualquier otro ejercicio.',
    technique: 'Enrolla la columna vértebra a vértebra. La cadera no se mueve: no es una flexión de cadera.',
  },
];

/** Pruebas físicas iniciales del módulo de tests (§39). */
export interface SeedTest {
  slug: string;
  name: string;
  unit: string;
  category: string;
  lowerIsBetter: boolean;
}

export const TEST_LIBRARY: SeedTest[] = [
  { slug: 'peso', name: 'Peso corporal', unit: 'kg', category: 'Antropometría', lowerIsBetter: false },
  { slug: 'altura', name: 'Altura', unit: 'cm', category: 'Antropometría', lowerIsBetter: false },
  { slug: 'cmj', name: 'Salto CMJ', unit: 'cm', category: 'Potencia', lowerIsBetter: false },
  { slug: 'sprint-10', name: 'Sprint 10 m', unit: 's', category: 'Velocidad', lowerIsBetter: true },
  { slug: 'sprint-20', name: 'Sprint 20 m', unit: 's', category: 'Velocidad', lowerIsBetter: true },
  { slug: 'sprint-30', name: 'Sprint 30 m', unit: 's', category: 'Velocidad', lowerIsBetter: true },
  { slug: 'yoyo', name: 'Yo-Yo IR1', unit: 'm', category: 'Resistencia', lowerIsBetter: false },
  { slug: 'course-navette', name: 'Course Navette', unit: 'palier', category: 'Resistencia', lowerIsBetter: false },
  { slug: 'agilidad-5105', name: 'Agilidad 5-10-5', unit: 's', category: 'Agilidad', lowerIsBetter: true },
  { slug: 'rm-banca', name: '1RM press banca', unit: 'kg', category: 'Fuerza', lowerIsBetter: false },
  { slug: 'rm-sentadilla', name: '1RM sentadilla', unit: 'kg', category: 'Fuerza', lowerIsBetter: false },
  { slug: 'dominadas-max', name: 'Dominadas máximas', unit: 'reps', category: 'Fuerza', lowerIsBetter: false },
  { slug: 'flexiones-max', name: 'Flexiones máximas', unit: 'reps', category: 'Fuerza', lowerIsBetter: false },
];
