import type { ExerciseCategory, MetricType } from '@/types/db';

export interface SeedExercise {
  /** Clave estable para referenciar el ejercicio desde las sesiones demo. */
  slug: string;
  name: string;
  category: ExerciseCategory;
  metricType: MetricType;
  movementType: string;
  muscles: string[];
  equipment: string[];
  description: string;
  technique: string;
}

/**
 * Biblioteca inicial de LORDGYM (§34). Son ejercicios globales:
 * `owner_coach_id = null`, visibles para todos los entrenadores y no editables.
 */
export const EXERCISE_LIBRARY: SeedExercise[] = [
  // --- Pecho ---------------------------------------------------------------
  {
    slug: 'press-banca',
    name: 'Press banca',
    category: 'pecho',
    metricType: 'strength',
    movementType: 'Empuje horizontal',
    muscles: ['Pectoral mayor', 'Tríceps', 'Deltoides anterior'],
    equipment: ['Barra', 'Banco'],
    description: 'Empuje horizontal con barra tumbado en banco plano.',
    technique: 'Escápulas retraídas, pies firmes, barra a la línea del pecho y empuje sin perder el arco.',
  },
  {
    slug: 'press-banca-mancuernas',
    name: 'Press banca con mancuernas',
    category: 'pecho',
    metricType: 'strength',
    movementType: 'Empuje horizontal',
    muscles: ['Pectoral mayor', 'Tríceps'],
    equipment: ['Mancuernas', 'Banco'],
    description: 'Variante unilateral que permite mayor recorrido y control escapular.',
    technique: 'Codos a 45°, muñecas neutras, baja hasta notar estiramiento sin forzar el hombro.',
  },
  {
    slug: 'press-inclinado',
    name: 'Press inclinado',
    category: 'pecho',
    metricType: 'strength',
    movementType: 'Empuje inclinado',
    muscles: ['Pectoral superior', 'Deltoides anterior'],
    equipment: ['Barra', 'Banco inclinado'],
    description: 'Press con banco a 30–45° que enfatiza la porción clavicular.',
    technique: 'Evita elevar los hombros; la barra baja a la parte alta del pecho.',
  },
  {
    slug: 'flexiones',
    name: 'Flexiones',
    category: 'pecho',
    metricType: 'bodyweight',
    movementType: 'Empuje horizontal',
    muscles: ['Pectoral', 'Tríceps', 'Core'],
    equipment: [],
    description: 'Empuje horizontal con peso corporal.',
    technique: 'Cuerpo en línea, glúteo activo, codos cerca del tronco.',
  },
  {
    slug: 'fondos',
    name: 'Fondos en paralelas',
    category: 'pecho',
    metricType: 'bodyweight',
    movementType: 'Empuje vertical',
    muscles: ['Pectoral inferior', 'Tríceps'],
    equipment: ['Paralelas'],
    description: 'Empuje vertical descendente en paralelas.',
    technique: 'Ligera inclinación del tronco, baja hasta 90° de codo sin hundir el hombro.',
  },

  // --- Espalda -------------------------------------------------------------
  {
    slug: 'dominadas',
    name: 'Dominadas',
    category: 'espalda',
    metricType: 'bodyweight',
    movementType: 'Tracción vertical',
    muscles: ['Dorsal ancho', 'Bíceps', 'Romboides'],
    equipment: ['Barra fija'],
    description: 'Tracción vertical con agarre prono.',
    technique: 'Inicia deprimiendo escápulas; sube hasta pasar la barbilla sin balanceo.',
  },
  {
    slug: 'remo-mancuerna',
    name: 'Remo con mancuerna',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción horizontal',
    muscles: ['Dorsal ancho', 'Trapecio medio', 'Bíceps'],
    equipment: ['Mancuerna', 'Banco'],
    description: 'Tracción horizontal unilateral con apoyo en banco.',
    technique: 'Espalda neutra, tira con el codo hacia la cadera sin rotar el tronco.',
  },
  {
    slug: 'remo-barra',
    name: 'Remo con barra',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción horizontal',
    muscles: ['Dorsal ancho', 'Erectores', 'Trapecio'],
    equipment: ['Barra'],
    description: 'Remo con tronco inclinado a unos 45°.',
    technique: 'Bisagra de cadera, core firme, barra al ombligo.',
  },
  {
    slug: 'jalon-polea',
    name: 'Jalón al pecho',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción vertical',
    muscles: ['Dorsal ancho', 'Bíceps'],
    equipment: ['Polea alta'],
    description: 'Alternativa guiada a la dominada.',
    technique: 'Pecho arriba, lleva la barra a la clavícula sin echar el tronco atrás.',
  },
  {
    slug: 'peso-muerto',
    name: 'Peso muerto',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Bisagra de cadera',
    muscles: ['Isquiotibiales', 'Glúteo', 'Erectores'],
    equipment: ['Barra'],
    description: 'Levantamiento desde el suelo con bisagra de cadera.',
    technique: 'Barra pegada a la pierna, espalda neutra, extiende cadera y rodilla a la vez.',
  },
  {
    slug: 'face-pull',
    name: 'Face pull',
    category: 'espalda',
    metricType: 'strength',
    movementType: 'Tracción horizontal alta',
    muscles: ['Deltoides posterior', 'Trapecio medio', 'Manguito rotador'],
    equipment: ['Polea', 'Cuerda'],
    description: 'Tracción a la cara para salud del hombro.',
    technique: 'Codos altos, rotación externa al final del recorrido.',
  },

  // --- Hombro --------------------------------------------------------------
  {
    slug: 'press-militar',
    name: 'Press militar',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Empuje vertical',
    muscles: ['Deltoides', 'Tríceps', 'Core'],
    equipment: ['Barra'],
    description: 'Empuje vertical de pie con barra.',
    technique: 'Glúteo y abdomen activos, la barra pasa cerca de la cara, bloquea arriba.',
  },
  {
    slug: 'landmine-press',
    name: 'Landmine press',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Empuje inclinado unilateral',
    muscles: ['Deltoides anterior', 'Serrato', 'Core'],
    equipment: ['Barra', 'Landmine'],
    description: 'Empuje en diagonal muy amable con el hombro.',
    technique: 'Postura estable, empuja en diagonal ascendente y protrae la escápula al final.',
  },
  {
    slug: 'elevaciones-laterales',
    name: 'Elevaciones laterales',
    category: 'hombro',
    metricType: 'strength',
    movementType: 'Abducción',
    muscles: ['Deltoides medio'],
    equipment: ['Mancuernas'],
    description: 'Aislamiento del deltoides medio.',
    technique: 'Sube hasta la altura del hombro sin encoger el trapecio.',
  },

  // --- Brazo ---------------------------------------------------------------
  {
    slug: 'curl-biceps',
    name: 'Curl de bíceps',
    category: 'biceps',
    metricType: 'strength',
    movementType: 'Flexión de codo',
    muscles: ['Bíceps braquial', 'Braquial'],
    equipment: ['Mancuernas'],
    description: 'Flexión de codo con mancuernas.',
    technique: 'Codos pegados al tronco, sin balanceo lumbar.',
  },
  {
    slug: 'curl-martillo',
    name: 'Curl martillo',
    category: 'biceps',
    metricType: 'strength',
    movementType: 'Flexión de codo neutra',
    muscles: ['Braquiorradial', 'Bíceps'],
    equipment: ['Mancuernas'],
    description: 'Curl con agarre neutro.',
    technique: 'Muñeca neutra durante todo el recorrido.',
  },
  {
    slug: 'extension-triceps-polea',
    name: 'Extensión de tríceps en polea',
    category: 'triceps',
    metricType: 'strength',
    movementType: 'Extensión de codo',
    muscles: ['Tríceps'],
    equipment: ['Polea'],
    description: 'Aislamiento de tríceps en polea alta.',
    technique: 'Codos fijos, extiende completamente sin mover el hombro.',
  },

  // --- Pierna --------------------------------------------------------------
  {
    slug: 'sentadilla',
    name: 'Sentadilla',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Dominante de rodilla',
    muscles: ['Cuádriceps', 'Glúteo', 'Aductores'],
    equipment: ['Barra', 'Rack'],
    description: 'Sentadilla trasera con barra.',
    technique: 'Rodillas siguiendo la punta del pie, tronco firme, baja al menos a paralelo.',
  },
  {
    slug: 'sentadilla-bulgara',
    name: 'Sentadilla búlgara',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Unilateral dominante de rodilla',
    muscles: ['Cuádriceps', 'Glúteo'],
    equipment: ['Mancuernas', 'Banco'],
    description: 'Zancada elevada unilateral, clave en deportes de equipo.',
    technique: 'Pie trasero apoyado en el banco, baja controlando la rodilla delantera.',
  },
  {
    slug: 'peso-muerto-rumano',
    name: 'Peso muerto rumano',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Bisagra de cadera',
    muscles: ['Isquiotibiales', 'Glúteo'],
    equipment: ['Barra'],
    description: 'Bisagra de cadera con rodillas semiflexionadas.',
    technique: 'Lleva la cadera atrás, espalda neutra, baja hasta notar tensión isquiotibial.',
  },
  {
    slug: 'hip-thrust',
    name: 'Hip thrust',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Extensión de cadera',
    muscles: ['Glúteo mayor', 'Isquiotibiales'],
    equipment: ['Barra', 'Banco'],
    description: 'Extensión de cadera con apoyo escapular en banco.',
    technique: 'Barbilla al pecho, bloquea arriba apretando el glúteo sin hiperextender lumbar.',
  },
  {
    slug: 'nordic-curl',
    name: 'Nordic curl',
    category: 'prevencion',
    metricType: 'bodyweight',
    movementType: 'Excéntrico isquiotibial',
    muscles: ['Isquiotibiales'],
    equipment: ['Compañero o anclaje'],
    description: 'Ejercicio excéntrico de referencia para prevenir lesiones de isquiotibiales.',
    technique: 'Baja lo más lento posible manteniendo cadera extendida.',
  },
  {
    slug: 'elevacion-talones',
    name: 'Elevación de talones',
    category: 'pierna',
    metricType: 'strength',
    movementType: 'Flexión plantar',
    muscles: ['Gastrocnemio', 'Sóleo'],
    equipment: ['Step'],
    description: 'Trabajo de tríceps sural y rigidez del tobillo.',
    technique: 'Recorrido completo, pausa arriba de un segundo.',
  },

  // --- Core ----------------------------------------------------------------
  {
    slug: 'pallof-press',
    name: 'Pallof press',
    category: 'core',
    metricType: 'strength',
    movementType: 'Anti-rotación',
    muscles: ['Oblicuos', 'Transverso'],
    equipment: ['Polea', 'Banda'],
    description: 'Anti-rotación isométrica, muy transferible al gesto deportivo.',
    technique: 'Aleja las manos del pecho resistiendo la rotación; sin mover la cadera.',
  },
  {
    slug: 'plancha',
    name: 'Plancha frontal',
    category: 'core',
    metricType: 'time',
    movementType: 'Isométrico',
    muscles: ['Transverso', 'Recto abdominal'],
    equipment: [],
    description: 'Isométrico de core en posición prona.',
    technique: 'Pelvis en retroversión, glúteo activo, sin hundir lumbares.',
  },
  {
    slug: 'dead-bug',
    name: 'Dead bug',
    category: 'core',
    metricType: 'strength',
    movementType: 'Anti-extensión',
    muscles: ['Transverso', 'Recto abdominal'],
    equipment: [],
    description: 'Control lumbopélvico con movimiento contralateral.',
    technique: 'Zona lumbar pegada al suelo durante todo el movimiento.',
  },
  {
    slug: 'copenhagen-plank',
    name: 'Copenhagen plank',
    category: 'prevencion',
    metricType: 'time',
    movementType: 'Isométrico aductor',
    muscles: ['Aductores', 'Core'],
    equipment: ['Banco'],
    description: 'Isométrico de aductores usado en prevención de pubalgia.',
    technique: 'Pierna superior apoyada en el banco, cadera alineada.',
  },

  // --- Pliometría ----------------------------------------------------------
  {
    slug: 'box-jump',
    name: 'Box jump',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Salto vertical',
    muscles: ['Cuádriceps', 'Glúteo', 'Gemelos'],
    equipment: ['Cajón'],
    description: 'Salto vertical sobre cajón. Calidad por encima de cantidad.',
    technique: 'Aterriza suave y con rodillas alineadas; baja del cajón caminando.',
  },
  {
    slug: 'cmj',
    name: 'CMJ (salto con contramovimiento)',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Salto vertical',
    muscles: ['Extensores de cadera y rodilla'],
    equipment: [],
    description: 'Salto vertical con contramovimiento, referencia de potencia.',
    technique: 'Manos en la cadera, contramovimiento rápido, salto máximo.',
  },
  {
    slug: 'broad-jump',
    name: 'Broad jump',
    category: 'pliometria',
    metricType: 'distance',
    movementType: 'Salto horizontal',
    muscles: ['Glúteo', 'Isquiotibiales', 'Cuádriceps'],
    equipment: [],
    description: 'Salto horizontal a máxima distancia.',
    technique: 'Brazos acompañan, aterrizaje amortiguado con dos pies.',
  },
  {
    slug: 'depth-jump',
    name: 'Depth jump',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Ciclo estiramiento-acortamiento',
    muscles: ['Tríceps sural', 'Cuádriceps'],
    equipment: ['Cajón'],
    description: 'Caída desde cajón y salto inmediato. Alta demanda neuromuscular.',
    technique: 'Contacto con el suelo mínimo; sólo con base de fuerza previa.',
  },
  {
    slug: 'pogo-jumps',
    name: 'Pogo jumps',
    category: 'pliometria',
    metricType: 'jump',
    movementType: 'Rigidez de tobillo',
    muscles: ['Gemelos', 'Sóleo'],
    equipment: [],
    description: 'Saltos cortos y rápidos para trabajar rigidez del tobillo.',
    technique: 'Rodillas casi extendidas, rebota con el tobillo.',
  },

  // --- Velocidad y agilidad ------------------------------------------------
  {
    slug: 'sprint-10m',
    name: 'Sprint 10 m',
    category: 'velocidad',
    metricType: 'distance',
    movementType: 'Aceleración',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Aceleración corta desde parado.',
    technique: 'Salida con inclinación, primeros apoyos por detrás del centro de masas.',
  },
  {
    slug: 'sprint-20m',
    name: 'Sprint 20 m',
    category: 'velocidad',
    metricType: 'distance',
    movementType: 'Aceleración',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Aceleración media, referencia clásica en deportes de equipo.',
    technique: 'Transición progresiva de la inclinación a la posición erguida.',
  },
  {
    slug: 'sprint-30m',
    name: 'Sprint 30 m',
    category: 'velocidad',
    metricType: 'distance',
    movementType: 'Velocidad máxima',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Sprint hasta velocidad máxima.',
    technique: 'Zancada amplia y activa, contacto breve con el suelo.',
  },
  {
    slug: 'cambio-direccion',
    name: 'Cambios de dirección',
    category: 'agilidad',
    metricType: 'time',
    movementType: 'COD',
    muscles: ['Tren inferior', 'Core'],
    equipment: ['Conos'],
    description: 'Circuito de cambios de dirección a máxima intensidad.',
    technique: 'Baja el centro de gravedad antes del cambio y reorienta la cadera.',
  },
  {
    slug: 'test-5-10-5',
    name: '5-10-5 (pro agility)',
    category: 'agilidad',
    metricType: 'time',
    movementType: 'COD',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Test de agilidad con dos cambios de 180°.',
    technique: 'Frenada con pie externo y salida explosiva.',
  },
  {
    slug: 't-test',
    name: 'T-Test',
    category: 'agilidad',
    metricType: 'time',
    movementType: 'COD multidireccional',
    muscles: ['Tren inferior'],
    equipment: ['Conos'],
    description: 'Test en T con desplazamientos frontal, lateral y atrás.',
    technique: 'Sin cruzar los pies en el desplazamiento lateral.',
  },

  // --- Movilidad y prevención ---------------------------------------------
  {
    slug: 'movilidad-cadera',
    name: 'Movilidad de cadera 90/90',
    category: 'movilidad',
    metricType: 'time',
    movementType: 'Movilidad activa',
    muscles: ['Rotadores de cadera'],
    equipment: [],
    description: 'Rotación activa de cadera en posición 90/90.',
    technique: 'Tronco erguido, movimiento controlado sin compensar con lumbar.',
  },
  {
    slug: 'movilidad-toracica',
    name: 'Movilidad torácica en cuadrupedia',
    category: 'movilidad',
    metricType: 'time',
    movementType: 'Movilidad activa',
    muscles: ['Columna torácica'],
    equipment: [],
    description: 'Rotación torácica con mano en la nuca.',
    technique: 'Bloquea la lumbar y rota sólo desde la zona dorsal.',
  },
  {
    slug: 'movilidad-tobillo',
    name: 'Movilidad de tobillo en pared',
    category: 'movilidad',
    metricType: 'time',
    movementType: 'Dorsiflexión',
    muscles: ['Tobillo'],
    equipment: ['Pared'],
    description: 'Test y ejercicio de dorsiflexión.',
    technique: 'Talón en el suelo, rodilla hacia la pared sin abrir el pie.',
  },
  {
    slug: 'monster-walk',
    name: 'Monster walk con banda',
    category: 'prevencion',
    metricType: 'time',
    movementType: 'Activación glútea',
    muscles: ['Glúteo medio'],
    equipment: ['Banda elástica'],
    description: 'Activación de glúteo medio en desplazamiento lateral.',
    technique: 'Rodillas separadas, pasos cortos, sin balancear el tronco.',
  },
  {
    slug: 'isquios-excentrico',
    name: 'Excéntrico de isquiotibiales en deslizamiento',
    category: 'rehabilitacion',
    metricType: 'strength',
    movementType: 'Excéntrico',
    muscles: ['Isquiotibiales'],
    equipment: ['Deslizadores'],
    description: 'Progresión de fuerza excéntrica en fases de readaptación.',
    technique: 'Extiende las piernas lentamente manteniendo la cadera alta.',
  },
  {
    slug: 'propiocepcion-tobillo',
    name: 'Propiocepción unipodal',
    category: 'rehabilitacion',
    metricType: 'time',
    movementType: 'Estabilidad',
    muscles: ['Tobillo', 'Core'],
    equipment: ['Bosu opcional'],
    description: 'Equilibrio a una pierna, base de la readaptación de tobillo.',
    technique: 'Mirada al frente, rodilla ligeramente flexionada, sin apoyar la otra pierna.',
  },

  // --- Cardio --------------------------------------------------------------
  {
    slug: 'carrera-continua',
    name: 'Carrera continua',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Aeróbico',
    muscles: ['Sistema cardiovascular'],
    equipment: [],
    description: 'Trabajo aeróbico continuo a intensidad controlada.',
    technique: 'Respiración cómoda; mantén la zona de FC objetivo.',
  },
  {
    slug: 'bici-estatica',
    name: 'Bicicleta estática',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Aeróbico',
    muscles: ['Cuádriceps', 'Sistema cardiovascular'],
    equipment: ['Bicicleta'],
    description: 'Cardio de bajo impacto, útil en cargas altas o readaptación.',
    technique: 'Sillín a la altura de la cadera; cadencia estable.',
  },
  {
    slug: 'remo-ergometro',
    name: 'Remo ergómetro',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Aeróbico de cuerpo completo',
    muscles: ['Espalda', 'Piernas', 'Sistema cardiovascular'],
    equipment: ['Remo'],
    description: 'Cardio de cuerpo completo con bajo impacto articular.',
    technique: 'Secuencia piernas → tronco → brazos; vuelve en orden inverso.',
  },
  {
    slug: 'intervalos-30-30',
    name: 'Intervalos 30/30',
    category: 'cardio',
    metricType: 'cardio',
    movementType: 'Intervalos',
    muscles: ['Sistema cardiovascular'],
    equipment: [],
    description: '30 segundos de carrera intensa por 30 de recuperación.',
    technique: 'Mantén el ritmo objetivo en todas las repeticiones.',
  },
];

/** Pruebas físicas iniciales del módulo de tests (§39). */
export interface SeedTest {
  slug: string;
  name: string;
  unit: string;
  category: string;
  lowerIsBetter: boolean;
}

export const TEST_LIBRARY: SeedTest[] = [
  { slug: 'peso', name: 'Peso corporal', unit: 'kg', category: 'Antropometría', lowerIsBetter: false },
  { slug: 'altura', name: 'Altura', unit: 'cm', category: 'Antropometría', lowerIsBetter: false },
  { slug: 'cmj', name: 'Salto CMJ', unit: 'cm', category: 'Potencia', lowerIsBetter: false },
  { slug: 'sprint-10', name: 'Sprint 10 m', unit: 's', category: 'Velocidad', lowerIsBetter: true },
  { slug: 'sprint-20', name: 'Sprint 20 m', unit: 's', category: 'Velocidad', lowerIsBetter: true },
  { slug: 'sprint-30', name: 'Sprint 30 m', unit: 's', category: 'Velocidad', lowerIsBetter: true },
  { slug: 'yoyo', name: 'Yo-Yo IR1', unit: 'm', category: 'Resistencia', lowerIsBetter: false },
  { slug: 'course-navette', name: 'Course Navette', unit: 'palier', category: 'Resistencia', lowerIsBetter: false },
  { slug: 'agilidad-5105', name: 'Agilidad 5-10-5', unit: 's', category: 'Agilidad', lowerIsBetter: true },
  { slug: 'rm-banca', name: '1RM press banca', unit: 'kg', category: 'Fuerza', lowerIsBetter: false },
  { slug: 'rm-sentadilla', name: '1RM sentadilla', unit: 'kg', category: 'Fuerza', lowerIsBetter: false },
  { slug: 'dominadas-max', name: 'Dominadas máximas', unit: 'reps', category: 'Fuerza', lowerIsBetter: false },
  { slug: 'flexiones-max', name: 'Flexiones máximas', unit: 'reps', category: 'Fuerza', lowerIsBetter: false },
];
